name: actions

on: [push, pull_request]

jobs:
  lint_and_format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy pylint

      - name: Run isort
        run: |
          isort --check .
          isort .

      - name: Run Black
        run: |
          black --check .
          black .

      - name: Run flake8
        run: flake8 .

      - name: Run pylint
        run: pylint --disable=missing-docstring,invalid-name *.py

      - name: Run mypy
        run: mypy --strict .

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format: apply isort, black" || echo "No changes to commit"
          git push || echo "Nothing to push"
