name: actions

on: [push, pull_request]

jobs:
  lint_and_format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==23.12.1 isort==5.13.2 flake8==6.1.0 pylint==3.0.3 mypy==1.7.1

      - name: Create config files
        run: |
          # .flake8 config
          echo "[flake8]" > .flake8
          echo "max-line-length = 88" >> .flake8
          echo "ignore = E203, W291, W503" >> .flake8
          
          # .isort.cfg config
          echo "[settings]" > .isort.cfg
          echo "profile = black" >> .isort.cfg
          echo "lines_after_imports = 2" >> .isort.cfg

      - name: Run isort
        run: |
          isort --settings-file .isort.cfg .
          git diff --quiet || (git add . && git commit -m "Apply isort formatting")

      - name: Run Black
        run: |
          black .
          git diff --quiet || (git add . && git commit -m "Apply Black formatting")

      - name: Run flake8
        run: flake8 . || echo "Flake8 found issues, please fix them manually"

      - name: Run pylint
        run: |
          pylint --disable=missing-docstring,invalid-name,too-few-public-methods *.py || echo "Pylint found issues"

      - name: Run mypy
        run: mypy --strict . || echo "Mypy found type issues"

      - name: Push changes
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase
          git push || echo "No changes to push"
